self.addEventListener("install",e=>{
 e.waitUntil(
  caches.open("user-data").then(c=>c.addAll([
   "./","index.html","admin.html","arvind.html","manifest.json"
  ]))
 );
});
self.addEventListener("fetch",e=>{
 e.respondWith(caches.match(e.request).then(r=>r||fetch(e.request)));
});
